openapi: 3.0.1
info:
  title: API V1 API Partners Integrator Tags API
  version: v1
  contact:
    name: API Support
    email: support@shop-ware.com
security:
- api_partner_id: []
  api_secret: []
tags:
- name: Integrator Tags
paths:
  /api/v1/tenants/{tenant_id}/integrator_tags:
    parameters:
    - name: tenant_id
      in: path
      required: true
      example: '1'
      schema:
        type: integer
    get:
      summary: Get a list of all integrator tags
      tags:
      - Integrator Tags
      parameters:
      - name: page
        in: query
        required: false
        example: '1'
        schema:
          type: integer
      - name: per_page
        in: query
        required: false
        example: '30'
        schema:
          type: integer
      - name: updated_after
        in: query
        required: false
        format: date-time
        description: Filter response to only include records updated after a given time
        example: 2022-10-24T12%3A00%3A00%2B08%3A00
        schema:
          type: string
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                successful:
                  value:
                    results:
                    - id: 2
                      created_at: '2026-06-09T14:22:55Z'
                      updated_at: '2026-06-09T14:22:55Z'
                      taggable_type: Shop
                      taggable_id: 1
                      name: tag_name
                      value: tag_value
                    - id: 1
                      created_at: '2026-06-09T14:22:55Z'
                      updated_at: '2026-06-09T14:22:55Z'
                      taggable_type: Customer
                      taggable_id: 1
                      name: tag_name
                      value: tag_value
                    limit: 2
                    limited: false
                    total_count: 2
                    current_page: 1
                    total_pages: 1
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          description: Unique identifier of this record.
                        taggable_id:
                          type: integer
                          description: Entity identifier the tag attached to.
                        taggable_type:
                          type: string
                          description: Entity type the tag attached to.
                        name:
                          type: string
                          description: Tag Name.
                        value:
                          type: string
                          description: Tag Value.
                        created_at:
                          type: string
                          format: date-time
                          description: Date and time when record was created.
                        updated_at:
                          type: string
                          format: date-time
                          description: Date and time when record was last updated.
                  limit:
                    type: integer
                  limited:
                    type: boolean
                  total_count:
                    type: integer
                  current_page:
                    type: integer
                  total_pages:
                    type: integer
    post:
      summary: Create an integrator tag
      tags:
      - Integrator Tags
      parameters: []
      responses:
        '201':
          description: successful
          content:
            application/json:
              examples:
                successful:
                  value:
                    id: 2
                    created_at: '2026-06-09T14:22:58Z'
                    updated_at: '2026-06-09T14:22:58Z'
                    taggable_type: Customer
                    taggable_id: 1
                    name: TagName
                    value: ABC123
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: Unique identifier of this record.
                  taggable_id:
                    type: integer
                    description: Entity identifier the tag attached to.
                  taggable_type:
                    type: string
                    description: Entity type the tag attached to.
                  name:
                    type: string
                    description: Tag Name.
                  value:
                    type: string
                    description: Tag Value.
                  created_at:
                    type: string
                    format: date-time
                    description: Date and time when record was created.
                  updated_at:
                    type: string
                    format: date-time
                    description: Date and time when record was last updated.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - taggable_type
              - taggable_id
              - name
              - value
              properties:
                taggable_type:
                  type: string
                  minLength: 1
                  enum:
                  - Appointment
                  - Assignment
                  - CannedJob
                  - Category
                  - Customer
                  - GpException
                  - Inventory
                  - Payment
                  - PaymentTransaction
                  - PurchaseRecord
                  - Recommendation
                  - RepairOrder
                  - Shop
                  - Staff
                  - Status
                  - Vehicle
                  - Vendor
                  description: type of the entity to be tagged. [Appointment, Assignment, CannedJob, Category, Customer, GpException, Inventory, Payment, PaymentTransaction, PurchaseRecord, Recommendation, RepairOrder, Shop, Staff, Status, Vehicle, Vendor ]
                taggable_id:
                  type: integer
                  description: Entity ID.
                name:
                  type: string
                  minLength: 1
                  description: Tag name.
                value:
                  type: string
                  minLength: 1
                  description: Tag value.
              example:
                taggable_type: Customer
                taggable_id: 1
                name: TagName
                value: ABC123
  /api/v1/tenants/{tenant_id}/integrator_tags/{id}:
    parameters:
    - name: tenant_id
      in: path
      required: true
      example: '1'
      schema:
        type: integer
    - name: id
      in: path
      required: true
      example: '2'
      schema:
        type: integer
    get:
      summary: Get an integrator tag by ID
      tags:
      - Integrator Tags
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                successful:
                  value:
                    id: 2
                    created_at: '2026-06-09T14:23:04Z'
                    updated_at: '2026-06-09T14:23:04Z'
                    taggable_type: Shop
                    taggable_id: 1
                    name: tag_name
                    value: tag_value
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: Unique identifier of this record.
                  taggable_id:
                    type: integer
                    description: Entity identifier the tag attached to.
                  taggable_type:
                    type: string
                    description: Entity type the tag attached to.
                  name:
                    type: string
                    description: Tag Name.
                  value:
                    type: string
                    description: Tag Value.
                  created_at:
                    type: string
                    format: date-time
                    description: Date and time when record was created.
                  updated_at:
                    type: string
                    format: date-time
                    description: Date and time when record was last updated.
    put:
      summary: Update an integrator tag by ID
      tags:
      - Integrator Tags
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                successful:
                  value:
                    id: 2
                    created_at: '2026-06-09T14:23:07Z'
                    updated_at: '2022-11-11T02:05:00Z'
                    taggable_type: Customer
                    taggable_id: 1
                    name: TagName123
                    value: ABC456
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: Unique identifier of this record.
                  taggable_id:
                    type: integer
                    description: Entity identifier the tag attached to.
                  taggable_type:
                    type: string
                    description: Entity type the tag attached to.
                  name:
                    type: string
                    description: Tag Name.
                  value:
                    type: string
                    description: Tag Value.
                  created_at:
                    type: string
                    format: date-time
                    description: Date and time when record was created.
                  updated_at:
                    type: string
                    format: date-time
                    description: Date and time when record was last updated.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                taggable_type:
                  type: string
                  minLength: 1
                  enum:
                  - Appointment
                  - Assignment
                  - CannedJob
                  - Category
                  - Customer
                  - GpException
                  - Inventory
                  - Payment
                  - PaymentTransaction
                  - PurchaseRecord
                  - Recommendation
                  - RepairOrder
                  - Shop
                  - Staff
                  - Status
                  - Vehicle
                  - Vendor
                  description: type of the entity to be tagged. [Appointment, Assignment, CannedJob, Category, Customer, GpException, Inventory, Payment, PaymentTransaction, PurchaseRecord, Recommendation, RepairOrder, Shop, Staff, Status, Vehicle, Vendor ]
                taggable_id:
                  type: integer
                  description: Entity ID.
                name:
                  type: string
                  minLength: 1
                  description: Tag name.
                value:
                  type: string
                  minLength: 1
                  description: Tag value.
              example:
                taggable_type: Customer
                taggable_id: 1
                name: TagName123
                value: ABC456
    delete:
      summary: Delete an integrator tag by ID
      tags:
      - Integrator Tags
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                successful:
                  value: {}
              schema:
                type: object
                properties: {}
components:
  securitySchemes:
    api_partner_id:
      type: apiKey
      name: X-Api-Partner-Id
      in: header
    api_secret:
      type: apiKey
      name: X-Api-Secret
      in: header
