openapi: 3.0.1
info:
  title: API V1 API Partners Assignments API
  version: v1
  contact:
    name: API Support
    email: support@shop-ware.com
security:
- api_partner_id: []
  api_secret: []
tags:
- name: Assignments
paths:
  /api/v1/tenants/{tenant_id}/assignments:
    parameters:
    - name: tenant_id
      in: path
      required: true
      example: '1'
      schema:
        type: integer
    get:
      summary: Get a list of all assignments
      tags:
      - Assignments
      parameters:
      - name: page
        in: query
        required: false
        example: '1'
        schema:
          type: integer
      - name: per_page
        in: query
        required: false
        example: '30'
        schema:
          type: integer
      - name: updated_after
        in: query
        required: false
        example: 2022-10-24T12%3A00%3A00%2B08%3A00
        schema:
          type: string
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                successful:
                  value:
                    results:
                    - id: 1
                      created_at: '2026-06-09T14:21:40Z'
                      updated_at: '2026-06-09T14:21:40Z'
                      repair_order_id: 1
                      transfer_to_id: 3
                      transfer_from_id: 2
                      message: some message
                      accepted_at: '2026-06-09T14:21:40Z'
                      cancelled_at: null
                      integrator_tags:
                      - id: 1
                        created_at: '2026-06-09T14:21:40Z'
                        updated_at: '2026-06-09T14:21:40Z'
                        taggable_type: Assignment
                        taggable_id: 1
                        name: tag_name
                        value: tag_value
                    limit: 1
                    limited: false
                    total_count: 1
                    current_page: 1
                    total_pages: 1
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          description: Unique identifier of this record.
                        repair_order_id:
                          type: integer
                          description: Foreign key which points to the RepairOrder which is being transferred.
                        transfer_to_id:
                          type: integer
                          description: Foreign key which points to the Staff that is performing the transfer.
                        transfer_from_id:
                          type: integer
                          description: Foreign key which points to the Staff that is performing the transfer.
                        message:
                          type: string
                          description: The transfer message.
                        accepted_at:
                          type: string
                          nullable: true
                          format: date-time
                          description: Date and time when the transfer was accepted. Null if not accepted.
                        cancelled_at:
                          type: string
                          nullable: true
                          format: date-time
                          description: Date and time when the transfer was cancelled. Null if not cancelled.
                        integrator_tags:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                type: integer
                                description: The tag primary key.
                              taggable_id:
                                type: integer
                                description: Entity identifier the tag attached to.
                              taggable_type:
                                type: string
                                description: Entity type the tag attached to.
                              name:
                                type: string
                                description: Tag Name.
                              value:
                                type: string
                                description: Tag Value.
                              created_at:
                                type: string
                                format: date-time
                                description: The date and time when tag was created.
                              updated_at:
                                type: string
                                format: date-time
                                description: The date and time when tag was last updated.
                        created_at:
                          type: string
                          format: date-time
                          description: Date and time when record was created.
                        updated_at:
                          type: string
                          format: date-time
                          description: Date and time when record was last updated.
                  limit:
                    type: integer
                  limited:
                    type: boolean
                  total_count:
                    type: integer
                  current_page:
                    type: integer
                  total_pages:
                    type: integer
  /api/v1/tenants/{tenant_id}/assignments/{id}:
    parameters:
    - name: tenant_id
      in: path
      required: true
      example: '1'
      schema:
        type: integer
    - name: id
      in: path
      required: true
      example: '1'
      schema:
        type: integer
    get:
      summary: Get a specific assignment by ID
      tags:
      - Assignments
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                successful:
                  value:
                    id: 1
                    created_at: '2026-06-09T14:21:43Z'
                    updated_at: '2026-06-09T14:21:43Z'
                    repair_order_id: 1
                    transfer_to_id: 3
                    transfer_from_id: 2
                    message: some message
                    accepted_at: '2026-06-09T14:21:43Z'
                    cancelled_at: null
                    integrator_tags:
                    - id: 1
                      created_at: '2026-06-09T14:21:43Z'
                      updated_at: '2026-06-09T14:21:43Z'
                      taggable_type: Assignment
                      taggable_id: 1
                      name: tag_name
                      value: tag_value
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: Unique identifier of this record.
                  repair_order_id:
                    type: integer
                    description: Foreign key which points to the RepairOrder which is being transferred.
                  transfer_to_id:
                    type: integer
                    description: Foreign key which points to the Staff that is performing the transfer.
                  transfer_from_id:
                    type: integer
                    description: Foreign key which points to the Staff that is performing the transfer.
                  message:
                    type: string
                    description: The transfer message.
                  accepted_at:
                    type: string
                    nullable: true
                    format: date-time
                    description: Date and time when the transfer was accepted. Null if not accepted.
                  cancelled_at:
                    type: string
                    nullable: true
                    format: date-time
                    description: Date and time when the transfer was cancelled. Null if not cancelled.
                  integrator_tags:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          description: The tag primary key.
                        taggable_type:
                          type: string
                          description: Entity type the tag attached to.
                        taggable_id:
                          type: integer
                          description: Entity identifier the tag attached to.
                        name:
                          type: string
                          description: Tag Name.
                        value:
                          type: string
                          description: Tag Value.
                        created_at:
                          type: string
                          format: date-time
                          description: The date and time when tag was created.
                        updated_at:
                          type: string
                          format: date-time
                          description: The date and time when tag was last updated.
                  created_at:
                    type: string
                    format: date-time
                    description: Date and time when record was created.
                  updated_at:
                    type: string
                    format: date-time
                    description: Date and time when record was last updated.
  /api/v2/tenants/{tenant_id}/assignments:
    parameters:
    - name: tenant_id
      in: path
      required: true
      example: '1'
      schema:
        type: integer
    get:
      summary: Get a list of all assignments
      tags:
      - Assignments
      parameters:
      - name: cursor
        in: query
        required: false
        description: Encoded reference to the last record of the current page. It is empty for the first page.
        example: ''
        schema:
          type: string
      - name: per_page
        in: query
        required: false
        example: '1'
        schema:
          type: integer
      - name: updated_after
        in: query
        required: false
        example: 2022-10-24T12%3A00%3A00%2B08%3A00
        schema:
          type: string
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                successful:
                  value:
                    results:
                    - id: 1
                      created_at: '2026-06-09T14:27:39Z'
                      updated_at: '2026-06-09T14:27:39Z'
                      repair_order_id: 1
                      transfer_to_id: 3
                      transfer_from_id: 2
                      message: some message
                      accepted_at: '2026-06-09T14:27:39Z'
                      cancelled_at: null
                      integrator_tags:
                      - id: 1
                        created_at: '2026-06-09T14:27:39Z'
                        updated_at: '2026-06-09T14:27:39Z'
                        taggable_type: Assignment
                        taggable_id: 1
                        name: tag_name
                        value: tag_value
                    cursor: null
                    limit: 1
                    has_next_page: false
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          description: Unique identifier of this record.
                        repair_order_id:
                          type: integer
                          description: Foreign key which points to the RepairOrder which is being transferred.
                        transfer_to_id:
                          type: integer
                          description: Foreign key which points to the Staff that is performing the transfer.
                        transfer_from_id:
                          type: integer
                          description: Foreign key which points to the Staff that is performing the transfer.
                        message:
                          type: string
                          description: The transfer message.
                        accepted_at:
                          type: string
                          nullable: true
                          format: date-time
                          description: Date and time when the transfer was accepted. Null if not accepted.
                        cancelled_at:
                          type: string
                          nullable: true
                          format: date-time
                          description: Date and time when the transfer was cancelled. Null if not cancelled.
                        integrator_tags:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                type: integer
                                description: The tag primary key.
                              taggable_id:
                                type: integer
                                description: Entity identifier the tag attached to.
                              taggable_type:
                                type: string
                                description: Entity type the tag attached to.
                              name:
                                type: string
                                description: Tag Name.
                              value:
                                type: string
                                description: Tag Value.
                              created_at:
                                type: string
                                format: date-time
                                description: The date and time when tag was created.
                              updated_at:
                                type: string
                                format: date-time
                                description: The date and time when tag was last updated.
                        created_at:
                          type: string
                          format: date-time
                          description: Date and time when record was created.
                        updated_at:
                          type: string
                          format: date-time
                          description: Date and time when record was last updated.
                  limit:
                    type: integer
                  cursor:
                    type: string
                    nullable: true
                    description: A pagination token that allows you to fetch the next set of records in a paginated list.
                  has_next_page:
                    type: boolean
                    description: A boolean indicating whether there are more pages available after the current one.
  /api/v2/tenants/{tenant_id}/assignments/{id}:
    parameters:
    - name: tenant_id
      in: path
      required: true
      example: '1'
      schema:
        type: integer
    - name: id
      in: path
      required: true
      example: '1'
      schema:
        type: integer
    get:
      summary: Get a specific assignment by ID
      tags:
      - Assignments
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                successful:
                  value:
                    id: 1
                    created_at: '2026-06-09T14:27:42Z'
                    updated_at: '2026-06-09T14:27:42Z'
                    repair_order_id: 1
                    transfer_to_id: 3
                    transfer_from_id: 2
                    message: some message
                    accepted_at: '2026-06-09T14:27:42Z'
                    cancelled_at: null
                    integrator_tags:
                    - id: 1
                      created_at: '2026-06-09T14:27:42Z'
                      updated_at: '2026-06-09T14:27:42Z'
                      taggable_type: Assignment
                      taggable_id: 1
                      name: tag_name
                      value: tag_value
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: Unique identifier of this record.
                  repair_order_id:
                    type: integer
                    description: Foreign key which points to the RepairOrder which is being transferred.
                  transfer_to_id:
                    type: integer
                    description: Foreign key which points to the Staff that is performing the transfer.
                  transfer_from_id:
                    type: integer
                    description: Foreign key which points to the Staff that is performing the transfer.
                  message:
                    type: string
                    description: The transfer message.
                  accepted_at:
                    type: string
                    nullable: true
                    format: date-time
                    description: Date and time when the transfer was accepted. Null if not accepted.
                  cancelled_at:
                    type: string
                    nullable: true
                    format: date-time
                    description: Date and time when the transfer was cancelled. Null if not cancelled.
                  integrator_tags:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          description: The tag primary key.
                        taggable_type:
                          type: string
                          description: Entity type the tag attached to.
                        taggable_id:
                          type: integer
                          description: Entity identifier the tag attached to.
                        name:
                          type: string
                          description: Tag Name.
                        value:
                          type: string
                          description: Tag Value.
                        created_at:
                          type: string
                          format: date-time
                          description: The date and time when tag was created.
                        updated_at:
                          type: string
                          format: date-time
                          description: The date and time when tag was last updated.
                  created_at:
                    type: string
                    format: date-time
                    description: Date and time when record was created.
                  updated_at:
                    type: string
                    format: date-time
                    description: Date and time when record was last updated.
components:
  securitySchemes:
    api_partner_id:
      type: apiKey
      name: X-Api-Partner-Id
      in: header
    api_secret:
      type: apiKey
      name: X-Api-Secret
      in: header
